#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit, this file will also be sourced.

# --- DPI setup ---
xrandr --dpi 160        # Set DPI. Default bumped from 96 to 160 for HiDPI screens.

# --- Set wallpaper ---
setbg &

# --- OPTIONAL: load Xresources (uncomment if using xrdb patch) ---
# xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

# --- Autostart programs ---
autostart="mpd xcompmgr dunst unclutter pipewire remapd"

for program in $autostart; do
    pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# --- Wait for xrdb if used ---
[ -n "$xrdbpid" ] && wait "$xrdbpid"

# --- Force dwm to reload after setting wallpaper ---
# This simulates the Mod+Shift+R (restart) or sends a SIGUSR1 depending on your patch.
# Most LARBS builds include the "dwm-attachbelow" restart binding which is actually SIGHUP.
pkill -HUP dwm
